version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "1234:1234"
    volumes:
      - gem_cache:/usr/local/bundle/gems
#    env_file: .env
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://vlad:president@database:5432/kittens_store_dev
  database:
    image: postgres:12.1
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  gem_cache: